name: Keep Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pagopa/dx/.github/actions/keep-alive@main
