name: Keep Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pagopa/dx/actions/keep-alive@main
        with:
          bot_token: ${{ secrets.GITHUB_TOKEN }}
